# Generated by Django 3.2 on 2023-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicornapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
